name: Node Backend CI

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Executing pull on branch push
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_FILE }}
          port: ${{ secrets.PORT }}
          script: "cd /var/www/html/app-dev.ultimatehealth.in/cicd-demo && git checkout main && git pull origin main"